export const DI_USUARIO_SCHEMA = "usuario";
export const DI_USUARIO_REPOSITORY = "USUARIO_REPOSITORY";

export const DI_AUDITORIA_SCHEMA = "auditoria";
export const DI_AUDITORIA_REPOSITORY = "AUDITORIA_REPOSITORY";